version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
        - "6379"
  rabbitmq:
    image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_USER=hotex
      - RABBITMQ_DEFAULT_PASS=hotex
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - /home/mongo/data:/data/db
      - /home/mongo/backups:/backups
    ports:
      - "28515:28515"
  textrade:
    container_name: textrade
    restart: on-failure
    build: .
    ports:
      - "8080"
    links:
      - mongodb:hotexdb
      - redis:redis
      - rabbitmq:rabbitmq
  nginx:
    build: ./VTextrade
    container_name: nginx-vtextrade
    links:
        - textrade:textrade
    ports:
        - "80:80"